# === Warm Light Orange Theme ===

background               #fffbf5
foreground               #262626

selection_foreground     #ffffff
selection_background     #fb521c

active_border_color      #fb521c
inactive_border_color    #c59752

active_tab_foreground    #ffffff
active_tab_background    #fb521c
inactive_tab_foreground  #262626
inactive_tab_background  #ffe36e

# 16 main colors
color0   #262626
color1   #c03900
color2   #a3a900
color3   #caae00
color4   #bd6c00
color5   #fb5d00
color6   #f79400
color7   #6a4e29
color8   #aaaaaa
color9   #ff8b67
color10  #f6ff3f
color11  #ffe36e
color12  #ffbd54
color13  #fc874f
color14  #c59752
color15  #1a1a1a

# Cursor
cursor                   #fb521c
cursor_text_color        #ffffff

# Links
url_color                #c03900
