=== Custom Orange Warm Theme ===

# Selección
selection_foreground     #ffffff
selection_background     #ff6a2a

# Tabs
active_tab_foreground    #ffffff
active_tab_background    #ff6a2a

inactive_tab_foreground  #3a3a3a
inactive_tab_background  #ffd6a5

# 16-colors (ajustados al esquema cálido con más vida)
color0   #1c1c1c
color1   #e06b4a
color2   #8ebd1a
color3   #d2a108
color4   #ff9a3c
color5   #b36ac0
color6   #f8a327
color7   #d4a373
color8   #bdbdbd
color9   #ff9777
color10  #d6ff66
color11  #ffe680
color12  #ffb347
color13  #ff7f50
color14  #ffd6a5
color15  #fffaf2

 
# Cursor
cursor                   #ff6a2a
cursor_text_color        #ffffff

# Links
url_color                #d94e1f

